### ISSUE TITLE
Region referance from frile not working

### ISSUE THREAD

**Issue by peterkup** [codecentric/serverless-plugin-cloudwatch-dashboard#3]
I'm this structure to reference different region in dependence to stage:
```
provider:
  versionFunctions: false
  name: aws
  runtime: python3.8
  region: ${file(serverless-resources/parameters.json):${opt:stage}.region}
```
And in cloud formation instead actual value it puts "${file(serverless-resources/parameters.json):${opt:stage}.region}".

![image](https://user-images.githubusercontent.com/25723611/108117193-42595e80-70a5-11eb-8d84-a4a8643ccfcf.png)

This issue only present for this particular plugin so I think there should be a bug.
